/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
const Human = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./models/human1124.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions?.man?.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='HankALL' rotation={[Math.PI / 2, 0, 0]} scale={0.01} />

        <group
          name='Armature'
          rotation={[0, 0.4, 0]}
          scale={0.01}
          position={[30.4, -39, 27]}
        >
          <primitive object={nodes.Root} />

          <skinnedMesh
            name='Hank_hair'
            geometry={nodes.Hank_hair.geometry}
            material={materials.hair}
            skeleton={nodes.Hank_hair.skeleton}
          />

          <skinnedMesh
            name='Hank_Bracelet'
            geometry={nodes.Hank_Bracelet.geometry}
            material={materials.glass}
            skeleton={nodes.Hank_Bracelet.skeleton}
          />
          <skinnedMesh
            name='Hank_earrings'
            geometry={nodes.Hank_earrings.geometry}
            material={materials.glass}
            skeleton={nodes.Hank_earrings.skeleton}
          />
          <skinnedMesh
            name='Hank_glass'
            geometry={nodes.Hank_glass.geometry}
            material={materials.glass}
            skeleton={nodes.Hank_glass.skeleton}
          />
          <skinnedMesh
            name='Hank_body'
            geometry={nodes.Hank_body.geometry}
            material={materials.body}
            skeleton={nodes.Hank_body.skeleton}
          />
          <skinnedMesh
            name='Hank_hand'
            geometry={nodes.Hank_hand.geometry}
            material={materials.hand}
            skeleton={nodes.Hank_hand.skeleton}
          />
          <skinnedMesh
            name='Hank_coat'
            geometry={nodes.Hank_coat.geometry}
            material={materials.coat}
            skeleton={nodes.Hank_coat.skeleton}
          />
          <skinnedMesh
            name='Hank_leg'
            geometry={nodes.Hank_leg.geometry}
            material={materials.leg}
            skeleton={nodes.Hank_leg.skeleton}
          />
          <skinnedMesh
            name='Hank_shoes_L'
            geometry={nodes.Hank_shoes_L.geometry}
            material={materials.shoes_L}
            skeleton={nodes.Hank_shoes_L.skeleton}
          />
          <skinnedMesh
            name='Hank_pant'
            geometry={nodes.Hank_pant.geometry}
            material={materials.pant}
            skeleton={nodes.Hank_pant.skeleton}
          />
          <skinnedMesh
            name='Hank_shoes_R'
            geometry={nodes.Hank_shoes_R.geometry}
            material={materials.shoes_R}
            skeleton={nodes.Hank_shoes_R.skeleton}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('./models/human1124.glb');

export default Human;
