/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Human(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./models/human.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='Hank_body'
          castShadow
          receiveShadow
          geometry={nodes.Hank_body.geometry}
          material={materials['body.001']}
          position={[-13.22, 0, -38.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_hair'
          castShadow
          receiveShadow
          geometry={nodes.Hank_hair.geometry}
          material={materials['hair.001']}
          position={[-13.22, 0, -38.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_Bracelet'
          castShadow
          receiveShadow
          geometry={nodes.Hank_Bracelet.geometry}
          material={materials['glass.001']}
          position={[-12.91, 0.59, -38.05]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_earrings'
          castShadow
          receiveShadow
          geometry={nodes.Hank_earrings.geometry}
          material={materials['glass.001']}
          position={[-13.22, 0, -38.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_glass'
          castShadow
          receiveShadow
          geometry={nodes.Hank_glass.geometry}
          material={materials['glass.001']}
          position={[-13.22, 0, -38.08]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_hand'
          castShadow
          receiveShadow
          geometry={nodes.Hank_hand.geometry}
          material={materials['hand.001']}
          position={[-13.22, 0, -38.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_coat'
          castShadow
          receiveShadow
          geometry={nodes.Hank_coat.geometry}
          material={materials['coat.001']}
          position={[-13.22, 0, -38.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_leg'
          castShadow
          receiveShadow
          geometry={nodes.Hank_leg.geometry}
          material={materials['leg.001']}
          position={[-13.22, 0, -38.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_shoes_L'
          castShadow
          receiveShadow
          geometry={nodes.Hank_shoes_L.geometry}
          material={materials['shoes_L.001']}
          position={[-13.22, 0, -38.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_pant'
          castShadow
          receiveShadow
          geometry={nodes.Hank_pant.geometry}
          material={materials['pant.001']}
          position={[-13.22, 0, -38.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <mesh
          name='Hank_shoes_R'
          castShadow
          receiveShadow
          geometry={nodes.Hank_shoes_R.geometry}
          material={materials['shoes_R.001']}
          position={[-13.1, 0, -38.07]}
          rotation={[-Math.PI, 0.09, -Math.PI]}
          scale={0.03}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./models/human.glb');

export default Human;
