/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/scooter.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Empty004' position={[-33.11, 0, 49.65]} scale={52.27} />
        <group name='Armature002' rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.Bip_01} />
          <skinnedMesh
            name='bag1'
            geometry={nodes.bag1.geometry}
            material={materials['lambert6.001']}
            skeleton={nodes.bag1.skeleton}
          />
          <skinnedMesh
            name='bag1001'
            geometry={nodes.bag1001.geometry}
            material={materials['lambert6.001']}
            skeleton={nodes.bag1001.skeleton}
          />
          <skinnedMesh
            name='body_fly_out'
            geometry={nodes.body_fly_out.geometry}
            material={materials['lambert6.001']}
            skeleton={nodes.body_fly_out.skeleton}
          />
          <skinnedMesh
            name='box'
            geometry={nodes.box.geometry}
            material={materials['lambert6.001']}
            skeleton={nodes.box.skeleton}
          />
          <skinnedMesh
            name='handle'
            geometry={nodes.handle.geometry}
            material={materials['lambert6.001']}
            skeleton={nodes.handle.skeleton}
          />
          <skinnedMesh
            name='support_L'
            geometry={nodes.support_L.geometry}
            material={materials['lambert6.001']}
            skeleton={nodes.support_L.skeleton}
          />
          <skinnedMesh
            name='supportube_R'
            geometry={nodes.supportube_R.geometry}
            material={materials['lambert6.001']}
            skeleton={nodes.supportube_R.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scooter.glb');
